#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${SCRIPT_DIR}/../docker/activemq" || exit 1

case "$1" in
  up)
    sudo docker-compose up --build -d
    ;;
  down)
    sudo docker-compose down
    ;;
  restart)
    sudo docker-compose down && sudo docker-compose up --build -d
    ;;
  *)
    echo "Usage: $0 {up|down|restart}"
    exit 1
    ;;
esac
